### ISSUE TITLE
0.2 bug fixes + minor additions

### ISSUE THREAD

**Issue by rscharff23** [TrevorBushnell/livesplit_parser#16]
add ability to exclude extreme outliers/add time minimum for plots (ex. minimum time shown = 26:00)

add .drop_na ability to all plots (maybe make the default = True as well)

'sec' in splits crashes trevors plots L (line139 in parser)

time distribution showing all points below/above average ? ex. uvid 70 star ttc

**Comment by TrevorBushnell** [comment]
In regards to computing averages...

If we want to drop NA values, then we need to take that into account when computing the averages... so after the check for `drop_na` param and then `pd.drop_na(inplace=True)`, we need to compute the average from THAT new dataframe.

**Comment by rscharff23** [comment]
outlier exclusion for plots calculating averages, goes along w #4
