### ISSUE TITLE
Expose GameTime

### ISSUE THREAD

**Issue by BrainStone** [TrevorBushnell/livesplit_parser#28]
GameTime is a very important metric that should absolutely be included in the data, as many games use GameTime instead of RealTime.

**Comment by TrevorBushnell** [comment]
I'm going to start working towards another release, would you like me to work on this or had you already started this implementation? I know that you had talked about starting it in the PR conversation we had earlier so I don't want to step on your toes if you had already been making progress :)

**Comment by BrainStone** [comment]
No. I haven't started working on it. Feel free to do it yourself.

**Comment by TrevorBushnell** [comment]
Sounds good, I will have this finished and will create another release with your two changes by the end of the day tomorrow so that you can start using it for your project :)

**Comment by BrainStone** [comment]
Any updates here? :)
